<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error Handling in ES6</title>
</head>
<body>
<b>Description:</b>
<br/>
Here, Try catch doesn't work synchronously.
<script>
    try {
        setTimeout(function (){
            blabla;
        }, 3000)
    }catch (e) {
        console.log('Error has occurred');
    }

</script>
</body>
</html>